services:
  _defaults:
    autowire: true
    public: true

  HeimrichHannot\NewsPaginationBundle\EventListener\HookListener: ~

  HeimrichHannot\NewsPaginationBundle\EventListener\ReaderBeforeRenderEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.reader.event.reader_before_render, method: addNewsPagination }
