services:
  _defaults:
    autowire: true
    public: true

  HeimrichHannot\NewsPaginationBundle\:
    resource: '../../{DataContainer,EventListener,Manager,Util}/*'

  HeimrichHannot\NewsPaginationBundle\EventListener\ReaderBeforeRenderEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.reader.event.reader_before_render, method: addNewsPagination }

  HeimrichHannot\NewsPaginationBundle\EventListener\ReaderModifyRetrievedItemEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.reader.event.reader_modify_retrieved_item, method: __invoke }
